#!/bin/sh
CICD=true
WORKSPACE=/opt/
JOB_BASE_NAME=Test_demo
BUILD_NUMBER=10
if [ $CICD = true ]
then
 echo "CI/CD pipe line check"
file="${WORKSPACE}/docker.sh"
REPORTNAME=${JOB_BASE_NAME}_${BUILD_NUMBER}.Test_demo_10
echo "CICD Check starting"
  if [ -f "$file" ]; then
        echo "testReport file found sending to artifactory"
        curl -X PUT -T $file  -u admin http://13.232.210.203:8082/artifactory/example-repo-local/
   else
   echo "testReport file not found"
  fi
fi
